version: '3.4'

services:
  thumamina:
    image: thumamina
    build:
      context: frontend/thumamina
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4303:4303
